name: Create Release and Pack Zip

on:
  # 触发条件：当创建新的 Release 时自动运行
  release:
    types: [published]
  # 允许通过Web界面手动触发
  workflow_dispatch:
permissions: 
    contents: write packages:write
jobs:

  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. 获取你的代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 将 luogu 文件夹打包成 ZIP
      - name: Pack luogu directory to zip
        run: |
          zip -r luogu-release-v${{ github.event.release.tag_name }}.zip ./luogu/

      # 3. 将打好的 ZIP 包上传到当前 Release
# ... 其他部分保持不变
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # 使用PAT而不是默认的GITHUB_TOKEN
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./luogu-release-v${{ github.event.release.tag_name }}.zip
          asset_name: luogu-release-v${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
