name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js (如果是JavaScript项目)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      run: npm run build
      
    - name: Create ZIP package
      run: |
        mkdir -p dist
        zip -r release-package-${{ github.ref_name }}.zip . \
          -x "*.git*" "node_modules/*" "*.github/*" "*.vscode/*"
          
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-package-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
